import {
  Entity,
  Column,
  OneToMany,
  Index,
} from 'typeorm';
import { Exclude } from 'class-transformer';
import { BaseEntity } from '@database/base.entity';
import { Role } from '@common/enums/role.enum';
import { UserStatus } from '@common/enums/status.enum';
import type { Salon } from '@modules/salon/entities/salon.entity';
import type { Staff } from '@modules/staff/entities/staff.entity';
import type { Barber } from '@modules/barber/entities/barber.entity';
import type { Notification } from '@modules/notification/entities/notification.entity';
import type { ActivityLog } from '@modules/activity-log/entities/activity-log.entity';
import type { Review } from '@modules/review/entities/review.entity';

/**
 * TypeORM entity representing a registered platform user.
 *
 * Maps to the `users` table. A single user account may be associated
 * with multiple roles across the system (owner, staff, barber, customer)
 * through their respective relationship collections. The `passwordHash`
 * column is excluded from serialized responses via `class-transformer`.
 *
 * A composite index on `[email, deletedAt]` supports efficient soft-delete
 * aware lookups, and an individual index on `status` accelerates filtering
 * by account state.
 */
@Entity('users')
@Index(['email', 'deletedAt'])           // partial-like index for active-user lookups
export class User extends BaseEntity {

  /**
   * Full display name of the user.
   * Stored as `VARCHAR(100)`.
   */
  @Column({ type: 'varchar', length: 100 })
  name: string;

  /**
   * Unique email address used for login and communication.
   * Stored as `VARCHAR(150)` with a unique constraint.
   */
  @Column({ type: 'varchar', unique: true, length: 150 })
  email: string;

  /**
   * Optional contact phone number.
   * Stored as `VARCHAR(20)` with a unique constraint; `null` when not provided.
   */
  @Column({ type: 'varchar', unique: true, nullable: true, length: 20 })
  phone: string | null;

  /**
   * Bcrypt-hashed password.
   *
   * The `@Exclude()` decorator prevents this field from appearing in
   * serialized API responses. Stored in the `password_hash` column.
   */
  @Exclude()
  @Column({ type: 'varchar', name: 'password_hash' })
  passwordHash: string;

  /**
   * Role assigned to this user, determining their access level.
   * Defaults to `CUSTOMER` on creation.
   */
  @Column({ type: 'enum', enum: Role, default: Role.CUSTOMER })
  role: Role;

  /**
   * Current account status (e.g. ACTIVE, SUSPENDED, BANNED).
   * Indexed to support fast filtering by account state.
   *
   * @default UserStatus.ACTIVE
   */
  @Index()
  @Column({ type: 'enum', enum: UserStatus, default: UserStatus.ACTIVE })
  status: UserStatus;

  /**
   * URL pointing to the user's profile avatar image.
   * `null` when the user has not uploaded an avatar.
   */
  @Column({ type: 'text', nullable: true })
  avatarUrl: string | null;

  /**
   * Timestamp at which the user's email address was verified.
   * `null` if email verification is still pending.
   */
  @Column({ type: 'datetime', nullable: true })
  emailVerifiedAt: Date | null;

  /**
   * Timestamp at which the user's phone number was verified.
   * `null` if phone verification is still pending or no phone was provided.
   */
  @Column({ type: 'datetime', nullable: true })
  phoneVerifiedAt: Date | null;

  /**
   * Timestamp of the user's most recent successful authentication.
   * `null` if the user has never logged in.
   */
  @Column({ type: 'datetime', nullable: true })
  lastLoginAt: Date | null;

  // ─── Relationships ───────────────────────────────────────────────────────

  /**
   * Salons added/registered by this user.
   * Inverse side of {@link Salon.addedBy}.
   */
  @OneToMany('Salon', (salon: Salon) => salon.addedBy)
  ownedSalons: Salon[];

  /**
   * Salons that this user has verified during the onboarding process.
   * Inverse side of {@link Salon.verifier}.
   */
  @OneToMany('Salon', (salon: Salon) => salon.verifier)
  verifiedSalons: Salon[];

  /**
   * Staff profiles linked to this user account across different salons.
   * Inverse side of {@link Staff.user}.
   */
  @OneToMany('Staff', (staff: Staff) => staff.user)
  staffProfiles: Staff[];

  /**
   * Barber profiles linked to this user account across different salons.
   * Inverse side of {@link Barber.user}.
   */
  @OneToMany('Barber', (barber: Barber) => barber.user)
  barberProfiles: Barber[];

  /**
   * In-app notifications addressed to this user.
   * Inverse side of {@link Notification.user}.
   */
  @OneToMany('Notification', (n: Notification) => n.user)
  notifications: Notification[];

  /**
   * Activity log entries generated by actions performed by or on this user.
   * Inverse side of {@link ActivityLog.user}.
   */
  @OneToMany('ActivityLog', (log: ActivityLog) => log.user)
  activityLogs: ActivityLog[];

  /**
   * Reviews written by this user as a customer.
   * Inverse side of {@link Review.customer}.
   */
  @OneToMany('Review', (r: Review) => r.customer)
  reviews: Review[];

  /**
   * Reviews on which this user has posted a reply (e.g. as a salon owner).
   * Inverse side of {@link Review.repliedBy}.
   */
  @OneToMany('Review', (r: Review) => r.repliedBy)
  reviewReplies: Review[];
}
