import {
  PrimaryGeneratedColumn,
  CreateDateColumn,
  UpdateDateColumn,
  DeleteDateColumn,
} from 'typeorm';

/**
 * Abstract base entity that every domain entity in the application extends.
 *
 * Provides four common audit columns that are managed automatically by TypeORM:
 *  - `id`        — UUID v4 primary key, generated by the database.
 *  - `createdAt` — set once when the row is first inserted.
 *  - `updatedAt` — updated automatically on every save/update.
 *  - `deletedAt` — nullable; populated by TypeORM's soft-delete feature
 *                  (`repository.softDelete`). Rows with a non-null `deletedAt`
 *                  are excluded from all standard queries automatically.
 *
 * @abstract — do not instantiate directly; extend in each domain entity.
 */
export abstract class BaseEntity {
  /** UUID v4 primary key, auto-generated by the database. */
  @PrimaryGeneratedColumn('uuid')
  id: string;

  /** Timestamp of the row's initial insertion. Set once by TypeORM. */
  @CreateDateColumn({ type: 'datetime' })
  createdAt: Date;

  /** Timestamp of the most recent update to this row. Managed by TypeORM. */
  @UpdateDateColumn({ type: 'datetime' })
  updatedAt: Date;

  /**
   * Soft-delete timestamp. `null` means the record is active.
   * When populated via `repository.softDelete()`, the row is hidden from
   * standard find queries but remains in the database for audit purposes.
   */
  @DeleteDateColumn({ type: 'datetime', nullable: true })
  deletedAt: Date | null;
}
