import { Role } from '@common/enums/role.enum';

/**
 * Describes the claims embedded in the JSON Web Token (JWT) issued by the
 * authentication service upon successful login.
 *
 * The JWT library populates the standard `iat` and `exp` claims automatically
 * when the token is signed.  The application-specific claims (`sub`, `email`,
 * `role`) are set explicitly during token generation and consumed by the JWT
 * strategy when the token is validated on protected routes.
 *
 * @example
 * // Payload decoded from a signed JWT:
 * {
 *   sub:   "a1b2c3d4-...",
 *   email: "customer@example.com",
 *   role:  Role.CUSTOMER,
 *   iat:   1712300000,
 *   exp:   1712386400,
 * }
 */
export interface JwtPayload {
  /**
   * Subject claim — the UUID of the authenticated user.
   *
   * This is the primary identifier used to look up the user record in the
   * database after the token has been verified.
   */
  sub: string;   // user UUID

  /**
   * The e-mail address of the authenticated user at the time the token was
   * issued.  Used as a human-readable identifier in log entries and responses.
   */
  email: string;

  /**
   * The application role assigned to the user (e.g. `ADMIN`, `CUSTOMER`).
   * Guards use this claim for role-based access control without an additional
   * database round-trip.
   */
  role: Role;

  /**
   * "Issued at" Unix timestamp (seconds since epoch) set automatically by the
   * JWT signing library.  Optional because it may not be present in tokens
   * generated by third-party identity providers.
   */
  iat?: number;  // issued at  (set by JWT library)

  /**
   * "Expires at" Unix timestamp (seconds since epoch) set automatically by
   * the JWT signing library.  Optional because it may not be present in tokens
   * generated by third-party identity providers.
   */
  exp?: number;  // expires at (set by JWT library)
}
