import { ApiProperty } from '@nestjs/swagger';

/**
 * Represents revenue totals for a single time-series bucket (day, week, or month)
 * as determined by the requested {@link Granularity}.
 */
export class RevenuePeriodDto {
  /**
   * The bucket label for this period.
   * Format depends on granularity:
   * - Daily   → `YYYY-MM-DD`
   * - Weekly  → ISO week identifier
   * - Monthly → `YYYY-MM`
   */
  @ApiProperty({ example: '2026-03-15' }) period: string;

  /** Total gross revenue collected during this period (in the salon's currency). */
  @ApiProperty({ example: 1250.00 })      revenue: number;

  /** Total amount refunded to customers during this period. */
  @ApiProperty({ example: 50.00 })        refunds: number;

  /**
   * Net revenue after subtracting refunds from gross revenue.
   * Calculated as: `revenue - refunds`.
   */
  @ApiProperty({ example: 1200.00 })      netRevenue: number;

  /** Number of completed payment transactions recorded during this period. */
  @ApiProperty({ example: 42 })           transactionCount: number;
}

/**
 * Revenue breakdown for a single payment method (e.g. card, cash, mobile).
 */
export class RevenueByMethodDto {
  /**
   * The payment method identifier as stored on the payment record
   * (e.g. `card`, `cash`, `mobile_money`).
   */
  @ApiProperty({ example: 'card' })  method: string;

  /** Total revenue collected via this payment method. */
  @ApiProperty({ example: 850.00 })  revenue: number;

  /** Number of transactions processed via this payment method. */
  @ApiProperty({ example: 28 })      count: number;

  /**
   * Percentage share of total revenue attributed to this payment method.
   * Value is in the range `[0, 100]`.
   */
  @ApiProperty({ example: 68.00 })   percentage: number;
}

/**
 * Revenue breakdown for a single salon service offering.
 */
export class RevenueByServiceDto {
  /** UUID of the service. */
  @ApiProperty() serviceId: string;

  /** Display name of the service (e.g. `Haircut`, `Beard Trim`). */
  @ApiProperty() serviceName: string;

  /** Total revenue generated by this service across the reporting period. */
  @ApiProperty() revenue: number;

  /** Number of times this service was rendered and paid for. */
  @ApiProperty() count: number;

  /**
   * Average revenue per transaction for this service.
   * Calculated as: `revenue / count`.
   */
  @ApiProperty() avgRevenue: number;
}

/**
 * Top-level revenue report returned by the analytics revenue endpoint.
 *
 * Aggregates gross/net revenue figures and provides breakdowns by time period,
 * payment method, and individual service for the requested date range and scope.
 */
export class RevenueReportDto {
  /** Total gross revenue collected across the entire reporting period. */
  @ApiProperty({ example: 15200.00 })                        totalRevenue: number;

  /** Total amount refunded to customers across the entire reporting period. */
  @ApiProperty({ example: 320.00 })                          totalRefunds: number;

  /**
   * Net revenue for the entire reporting period after deducting refunds.
   * Calculated as: `totalRevenue - totalRefunds`.
   */
  @ApiProperty({ example: 14880.00 })                        netRevenue: number;

  /** Total number of payment transactions recorded in the reporting period. */
  @ApiProperty({ example: 480 })                             totalTransactions: number;

  /**
   * Time-series breakdown of revenue, one {@link RevenuePeriodDto} per bucket.
   * Ordered chronologically (earliest period first).
   */
  @ApiProperty({ type: [RevenuePeriodDto] })                 byPeriod: RevenuePeriodDto[];

  /**
   * Revenue breakdown grouped by payment method.
   * Ordered by revenue descending (highest-earning method first).
   */
  @ApiProperty({ type: [RevenueByMethodDto] })               byPaymentMethod: RevenueByMethodDto[];

  /**
   * Revenue breakdown grouped by service.
   * Ordered by revenue descending (highest-earning service first).
   */
  @ApiProperty({ type: [RevenueByServiceDto] })              byService: RevenueByServiceDto[];
}
